apiVersion: apps/v1
kind: Deployment

metadata:
  name: {{ .Release.Name }}-backend
  namespace: {{ .Release.Namespace }}
  labels:
    app: backend
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: {{ .Release.Name }}-backend
          image: "{{ .Values.global.image.registry }}/{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          env:
            - name: NODE_ENV
              value: {{ .Values.nodeEnv | quote  }}
            - name: HOST
              value: {{ .Values.host | quote  }}
            - name: PORT
              value: {{ .Values.port | quote }}
            - name: LOG_LEVEL
              value: {{ .Values.logLevel | quote  }}
            - name: APP_KEY
              value: {{ .Values.appKey | quote  }}
            - name: DB_HOST
              value: {{ .Values.postgres.host | quote  }}
            - name: DB_PORT
              value: {{ .Values.postgres.port | quote  }}
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.postgres.credentialsSecret }}
                  key: user
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.postgres.credentialsSecret }}
                  key: password
            - name: DB_DATABASE
              value: {{ .Values.postgres.database | quote  }}
      imagePullSecrets:
        - name: "{{ .Values.image.pullSecretName }}"
