apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-backend
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    app: backend
  ports:
    - protocol: TCP
      port: 80
      targetPort: {{ .Values.port }}
